### ISSUE TITLE
Make `WPMediaUtils` and `WPMediaUtilsWrapper` consistent 

### ISSUE THREAD

**Issue by wzieba** [wordpress-mobile/WordPress-MediaPicker-Android#28]
Original implementation had a wrapper around static `WPMediaUtils` in order to have testable code. We should make those two classes as a one, not static and testable dependency.

Preferably also rename it from `Utils` to something more related to navigating through Activities (as this is its main responsibility now).

**Comment by 0nko** [comment]
The code has been significantly refactored and the classes don't exist anymore.
