### ISSUE TITLE
Let consumer define request codes

### ISSUE THREAD

**Issue by wzieba** [wordpress-mobile/WordPress-MediaPicker-Android#45]
In MediaPicker we declare request codes in [`MediaPickerRequestCodes`](https://github.com/wordpress-mobile/WordPress-MediaPicker-Android/blob/c9f04192cb902f72ef55fca1f8c7d01e380dbd66/MediaPicker/src/main/java/org/wordpress/android/mediapicker/MediaPickerRequestCodes.kt). This might be problematic if consumer of the library already uses those request codes for some other action.

**Comment by 0nko** [comment]
Request codes have been replaced with `AcitivityResultContracts`, so this issue doesn't apply anymore.
